language: scala
scala:
  - 2.12.12
  - 2.13.3
jdk:
   - openjdk8
   - openjdk11
script:
  - travis_wait 30 sbt ++$TRAVIS_SCALA_VERSION clean test

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.sbt/1.3.13
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/cache
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete

